name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 8 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          plugin_habits: yes
          plugin_habits_facts: no
          plugin_habits_charts: yes
          config_timezone: Asia/Shanghai
          plugin_music: yes
          plugin_music_playlist: https://embed.music.apple.com/cn/playlist/j-s-bach-essentials/pl.4cc4518c3d7e4f4a8a80a6408911a7b1
          plugin_music_limit: 2
