name: Waka Readme

on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 */4 * * *"

jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_TOTAL_CODE_TIME: false
          SHOW_PROFILE_VIEWS: false
          SHOW_SHORT_INFO: false
          SHOW_LANGUAGE_PER_REPO: false
          SHOW_PROJECTS: false
          SHOW_TIMEZONE: false
          SHOW_OS: false