name: Update WakaTime stats

on:
  schedule:
    - cron: "30 2 * * *"
  workflow_dispatch:

jobs:
  update-readme:
    name: Update README
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: write
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_TOTAL_CODE_TIME: false
          SHOW_PROFILE_VIEWS: false
          SHOW_SHORT_INFO: false
          SHOW_LANGUAGE_PER_REPO: false
          SHOW_PROJECTS: false
          SHOW_TIMEZONE: false
          SHOW_OS: false
          SHOW_LOC_CHART: false
          SHOW_AI_CODE_TIME: false
